name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: jdk10

      - name: Get Artifact
        run: ./gradlew assemble

      - name: Create Artifact Path
        run: |
          mkdir -p opendistro-sql-builds
          cp -r ./build/distributions/*.zip opendistro-sql-builds/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: opendistro-sql
          path: opendistro-sql-builds
